#
# SPDX-License-Identifier: Apache-2.0
#
---
trigger:
  branches:
    include:
      - "*"
    exclude:
      - gh-pages
  tags:
    include:
      - "*"
pool:
  vmImage: "ubuntu-latest"
steps:
  - script: sudo apt-get update && sudo apt-get install -y shellcheck
    displayName: Install Ubuntu dependencies
  - task: GoTool@0
    inputs:
      version: "1.14"
    displayName: Use Go 1.14
  - script: make lint
    displayName: Run Go formatters and linters
  - script: make unit
    displayName: Run Go unit tests
  - script: shellcheck builders/*/bin/*
    displayName: Run ShellCheck